### ISSUE TITLE
Deprecated modules

### ISSUE THREAD

**Issue by WagnoLeaoSergio** [nano-react-app/template-js#12]
NPM is warning about some deprecated modules, is this somehow affect the way the app will work?

**Comment by adrianmcli** [comment]
I actually just left my job, so I'll be spending a lot more time on this. I didn't know this package got so popular! Thanks for bringing this to my attention.

**Comment by adrianmcli** [comment]
@WagnoLeaoSergio can you paste what the warning looks like?

**Comment by WagnoLeaoSergio** [comment]
Thanks for checking it out, here is the warning:

`>npm intstall`
`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`
`npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated`
`npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated`

**Comment by adrianmcli** [comment]
Running `npm ls` on the three packages you mentioned yielded the following result:

<img width="385" alt="Screen Shot 2020-05-10 at 3 09 54 PM" src="https://user-images.githubusercontent.com/943555/81508151-62672080-92d0-11ea-8041-f9afb26bbe12.png">

Since there are no security issues for these projects I don't see this as a major problem. They are simply deprecated but they can be expected to work as intended for the time being. If there's a security issue, I am glad to revisit this.

They are also deep dependencies of Parcel. It's probably more appropriate to post about that in their repo instead.

Sorry @WagnoLeaoSergio but there's not much we can do about this on our end. I'm closing this for now, let me know if you think it should be re-opened.
