### ISSUE TITLE
The CSS affected for each compilation.

### ISSUE THREAD

**Issue by cunguyendev** [nano-react-app/template-js#14]
Due to each compile, the cache will be spawned so it makes CSS affected.
The reality, there are some ways to avoid this:

- Open the incognito tab
- Use Ctrl + Shift + R (Windows/Linux) or Cmd + Shift + R (Mac)

**Comment by mgreasly** [comment]
@cunguyendev - I'm going to close the associated PR that you raised - we've updated the build to use ViteJS instead of Parcel so it's not appropriate any more. Not sure if this change will resolve the issue you're raising though - are you able to test the latest template to see if we still need to look at this?

**Comment by cunguyendev** [comment]
Thanks for the reply! I will test it.
