### ISSUE TITLE
Can not import css or scss files

### ISSUE THREAD

**Issue by ivanbkovacevic** [nano-react-app/template-js#2]
Hello from Serbia,
I like your idea with React Nano  but I can not import css or scss files.
Do you have more detailed documentation on how to use React Nano?
Thanks a lot

**Comment by nikrowell** [comment]
@ivanbkovacevic hello from Colorado! I was able to import a .scss file (both within the src directory, and outside of it as `import ../scss/index.scss`), but I had to kill the parcel process and restart it. Could be that parcel simply isn't detecting the new file due to it's caching. Does that work for you?

**Comment by ivanbkovacevic** [comment]
Hi.... hey ...it works  :)   thanks a lot buddy.
One more question ... is it ok to use Redux with React Nano ?

**Comment by adrianmcli** [comment]
@ivanbkovacevic you can use whatever you want :)

Thanks @nikrowell for answering this issue. And thanks to both of you for using Nano.

**Comment by pmsoltani** [comment]
To get it to work, I had to delete `.parcel-cache` dir and do `npm start` again.
